import { createClient } from '@supabase/supabase-js';
import { projectId as defaultProjectId, publicAnonKey as defaultAnonKey } from '../../utils/supabase/info';

// Environment variables from Vercel (optional override)
// Falls back to autogenerated values if not set
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || `https://${defaultProjectId}.supabase.co`;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || defaultAnonKey;

// Validation: Show clear error if neither source has valid values
if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error(
    'Missing Supabase configuration. ' +
    'Please ensure Supabase credentials are properly configured.'
  );
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    storageKey: 'yieldpulse-auth',
  },
});

export const getAuthToken = (): string | null => {
  const token = localStorage.getItem('yieldpulse-access-token');
  return token;
};

export const setAuthToken = (token: string): void => {
  localStorage.setItem('yieldpulse-access-token', token);
};

export const removeAuthToken = (): void => {
  localStorage.removeItem('yieldpulse-access-token');
};

// API URL constructed from Supabase URL
export const apiUrl = `${supabaseUrl}/functions/v1/make-server-ef294769`;

// Export for debugging (non-sensitive info only)
export const config = {
  supabaseUrl,
  hasAnonKey: !!supabaseAnonKey,
};
