import { createClient } from '@supabase/supabase-js';
import { projectId, publicAnonKey } from '../../utils/supabase/info';

// Environment variables from Vercel (optional override)
// Falls back to autogenerated values if not set
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || `https://${projectId}.supabase.co`;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || publicAnonKey;

// Validation: Show clear error if configuration is invalid
if (!supabaseUrl || !supabaseAnonKey) {
  console.error('❌ Missing Supabase configuration');
  throw new Error('Missing Supabase configuration. Please check environment variables.');
}

console.log('🔧 Supabase Configuration:', {
  url: supabaseUrl,
  keyPrefix: supabaseAnonKey.substring(0, 20) + '...',
  projectId: projectId
});

let supabaseClient;

try {
  supabaseClient = createClient(supabaseUrl, supabaseAnonKey, {
    auth: {
      persistSession: true,
      storageKey: 'yieldpulse-auth',
      autoRefreshToken: true,
      detectSessionInUrl: true, // CRITICAL: Required for email verification redirect to work
    },
    global: {
      headers: {
        'x-client-info': 'yieldpulse-web',
      },
      fetch: (url, options = {}) => {
        // Add timeout to all fetch requests
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 45000); // 45 second timeout
        
        return fetch(url, {
          ...options,
          signal: controller.signal,
        }).finally(() => clearTimeout(timeoutId));
      },
    },
    db: {
      schema: 'public',
    },
  });
  console.log('✅ Supabase client initialized successfully');
} catch (err) {
  console.error('❌ Failed to initialize Supabase client:', err);
  throw err;
}

export const supabase = supabaseClient;