import { createClient } from '@supabase/supabase-js';
import { projectId, publicAnonKey } from '../../utils/supabase/info';

// Environment variables from Vercel (optional override)
// Falls back to autogenerated values if not set
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || `https://${projectId}.supabase.co`;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || publicAnonKey;

// Validation: Show clear error if configuration is invalid
if (!supabaseUrl || !supabaseAnonKey) {
  console.error('❌ Missing Supabase configuration');
  throw new Error('Missing Supabase configuration. Please check environment variables.');
}

let supabaseClient;

try {
  supabaseClient = createClient(supabaseUrl, supabaseAnonKey, {
    auth: {
      persistSession: true,
      storageKey: 'yieldpulse-auth',
      autoRefreshToken: true,
      detectSessionInUrl: false,
    },
  });
  console.log('✅ Supabase client initialized successfully');
} catch (err) {
  console.error('❌ Failed to initialize Supabase client:', err);
  throw err;
}

export const supabase = supabaseClient;